
server:
  port: 8001
service-url:
  api: http://localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: ${service-url.api}/
          predicates:
            - Path=/user/**
